apiVersion: v1
kind: Pod
metadata:
  name: nginx-persistente
  labels:
    app: ng-persistente
spec:
  volumes:
    - name: nginx-storage
      persistentVolumeClaim:
        claimName: persistent-volume-claim
  containers:
    - name: nginx-persistente-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-storage
        volumes:
        - name: html-volume
          configMap:
            name: my-html-configmap
            defaultMode: 420

---
apiVersion: v1
kind: Service
metadata:
  name: np-svc
  labels:
     app: ng-persistente
spec:
  type: NodePort
  ports:
  - port: 80
    #nodePort: 30080
    protocol: TCP
  selector:
     app: ng-persistente
