apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 128MiB
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/persistent-volume"
